name: Mermaid Maker 
description: Convert mermaid files into image formats.
inputs:
  input_dir:
    description: the input directory for mermaid files
    required: false
    default: "all"
  input_file_extension:
    description: the extension of the mermaid files
    required: false
    default: "mmd"
  output_dir:
    description: the output directory for generated mermaid files
    required: false
    default: "same" 
  output_file_extension:
    description: the output format of the generated mermaid files
    required: false
    default: "svg"
  token: 
    description: |
      the PAT (personal access token) used to access and push changes
      to the github repo
    required: true

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

runs:
  using: composite
  steps:
    - uses: "actions/checkout@main"
      with:
        token: ${{inputs.token}}
    - uses: "actions/setup-node@main"
      with: 
        node-version: 26
    - run: PUPPETEER_SKIP_DOWNLOAD='true' npm install -g @mermaid-js/mermaid-cli
      shell: bash
    - name: Download a single artifact
      uses: actions/download-artifact@v8.0.1
      with:
        name: mermaid-maker-chrome-browser
      id: chrome-browser-download
      continue-on-error: true
    - name: install browser if doesnt exist
      if: ${{steps.chrome-browser-download.outcome == 'failure'}}
      run: PUPPETEER_CACHE_DIR='./mermaid-maker-chrome-browser' npx puppeteer browsers install
      shell: bash
    - if: ${{steps.chrome-browser-download.outcome == 'failure'}}
      name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: mermaid-maker-chrome-browser
        path: mermaid-maker-chrome-browser
        retention-days: 7
    - run: |
        if [[ ${{inputs.input_dir}} == "all" ]]; then
          echo "files_to_check=**.${{inputs.input_file_extension}}" >> "$GITHUB_OUTPUT"
        else
          echo "files_to_check=${{inputs.input_dir}}/**.${{inputs.input_file_extension}}" >> "$GITHUB_OUTPUT"
        fi
      id: get-files-to-check
      shell: bash
    - uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      id: changed_files
      with: 
        files: ${{steps.get-files-to-check.outputs.files_to_check}}
        since: 2022-04-30
      # if outpu_dir same:
        # output file with new suffix
      # if output_dir diff
        # extract file name
        # place under new dir
        # output file with new suffix 
    - if: ${{steps.changed_files.outputs.any_changed == 'true'}}
      env:
        ALL_CHANGED_FILES: ${{steps.changed_files.outputs.all_changed_files}}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          file_base=$(basename -s .${{inputs.input_file_extension}} ${file})
          original_file_dir=$(dirname ${file})
          if [[ ${{inputs.output_dir}} == "same" ]]; then
            PUPPETEER_CACHE_DIR=mermaid-maker-chrome-browser aa-exec --profile=chrome mmdc -i "$file" -o "${original_file_dir}/${file_base}.${{inputs.output_file_extension}}" -b transparent
          else
            aa-exec --profile=chrome mmdc -i "$file" -o "${{inputs.output_dir}}/${file_base}.${{inputs.output_file_extension}}" -b transparent
          fi
        done

      shell: bash
    - uses: EndBug/add-and-commit@v10
      with:
        message: "feat: Convert .mmd file(s) to svg"
    