name: Mermaid Maker 
description: Convert mermaid files into image formats.
inputs:
  input_dir:
    description: |
     The input directory for mermaid files. Defaults to "all",
     i.e. all changed files with input_file_extension across the whole repo.
    required: false
    default: "all"

  input_file_extension:
    description: The extension of the mermaid files. 
    required: false
    default: "mmd"

  output_dir:
    description: |
      The output directory for generated mermaid files. Defaults to "same",
      i.e. converted files will be placed in the same directory as their source files.
    required: false
    default: "same" 

  output_file_extension:
    description: |
      The output format of the generated mermaid files. Only "svg", "png"and "pdf" are accepted. 
    required: false
    default: "svg"

  commit_message:
    description: |
      The commit message used for commiting mermaid files into the repository. 
      Defaults to: "feat: Convert `input_file_extension` file(s) to `output_file_extension`".
    required: false
    default: ""

  pkg_manager:
    description: |
      The node package manager to use. Make sure it's setup before using this action.
      Currently, only the following pkg_managers are accepted:
        - "npm"   
        - "pnpm"  
        - "yarn" 
        - "bun"   
    required: false
    default: "npm"

branding:
  icon: arrow-down-circle
  color: purple

runs:
  using: composite
  steps:
    - name: get directory names to check for changes
      run: |
        if [[ ${{inputs.input_dir}} == "all" ]]; then
          echo "files_to_check=**/*.${{inputs.input_file_extension}}" >> "$GITHUB_OUTPUT"
        else
          echo "files_to_check=${{inputs.input_dir}}/**/*.${{inputs.input_file_extension}}" >> "$GITHUB_OUTPUT"
        fi
      id: get-files-to-check
      shell: bash

    ## check for changes files and exit early with no changes
    # TODO: add inputs and change variable names for next steps
    - id: changed_files
      name: check for missing/old outputted files
      run: |
        shopt -s globstar nullglob

        echo CHANGED_FILES="$(

            for file in ${{env.FILES_TO_CHECK}}; do

                FILE_DIRNAME=$(dirname "$file")
                FILE_BASENAME=$(basename -s ".${{inputs.input_file_extension}}" "$file")

                if [[ "${FILE_DIRNAME}/${FILE_BASENAME}.${{inputs.output_file_extension}}" -ot "$file" ]]; then
                
                    echo "${FILE_DIRNAME}/${FILE_BASENAME}"

                fi

            done
        )" >> "$GITHUB_OUTPUT"

        shopt -u globstar nullglob
      shell: bash
      env:
        FILES_TO_CHECK: ${{steps.get-files-to-check.outputs.files_to_check}}


    - if: ${{steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: Set pkg_manager run commmand
      run: |
        if [[ ${{inputs.pkg_manager}} == 'npm' ]]; then
            echo "pkg_manager_run_cmd=npx" >> "$GITHUB_OUTPUT"
        elif [[ ${{inputs.pkg_manager}} == 'pnpm' ]]; then
            echo "pkg_manager_run_cmd=pnpm" >> "$GITHUB_OUTPUT"
        elif [[ ${{inputs.pkg_manager}} == 'yarn' ]]; then
            echo "pkg_manager_run_cmd=yarn dlx" >> "$GITHUB_OUTPUT"
        elif [[ ${{inputs.pkg_manager}} == 'bun' ]]; then
            echo "pkg_manager_run_cmd=bunx" >> "$GITHUB_OUTPUT"
        else
            exit 1
        fi
      id: set_pkg_manager_run
      shell: bash

    - if: ${{steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: Package manager setup
      run: |
        if [[ ${{inputs.pkg_manager}} == 'npm' ]]; then
            echo "Nothing to setup" 
        elif [[ ${{inputs.pkg_manager}} == 'pnpm' ]]; then
            pnpm config set --location=project strictDepBuilds false
        elif [[ ${{inputs.pkg_manager}} == 'yarn' ]]; then
            echo "Nothing to setup"
        elif [[ ${{inputs.pkg_manager}} == 'bun' ]]; then
            echo "Nothing to setup" 
        else
            exit 1
        fi
      shell: bash


    # env variable is used to skip browser download, to instead use caching mechanisms
    - if: ${{steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: install mermaid
      run: PUPPETEER_SKIP_DOWNLOAD='true' ${{inputs.pkg_manager}} install @mermaid-js/mermaid-cli@11.16.0
      shell: bash
    
    - if: ${{steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: Package manager teardown
      run: |
        if [[ ${{inputs.pkg_manager}} == 'npm' ]]; then
            echo "Nothing to tear down" 
        elif [[ ${{inputs.pkg_manager}} == 'pnpm' ]]; then
            pnpm config set --location=project strictDepBuilds true
        elif [[ ${{inputs.pkg_manager}} == 'yarn' ]]; then
            echo "Nothing to tear down"
        elif [[ ${{inputs.pkg_manager}} == 'bun' ]]; then
            echo "Nothing to tear down" 
        else
            exit 1
        fi
      shell: bash



    - if: ${{steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: 'Cache mermaid browser'
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        # pin mermaid browser to mermaid version
        # in the future, this should be automated
        key: mermaid-maker-chrome-browser-11.16.0
        path: mermaid-maker-chrome-browser
      id: chrome_browser_download

    - if: ${{steps.chrome_browser_download.outputs.cache-hit != 'true' && steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: install browser if doesnt exist
      run: PUPPETEER_CACHE_DIR='./mermaid-maker-chrome-browser' ${{steps.set_pkg_manager_run.outputs.pkg_manager_run_cmd}} puppeteer browsers install
      shell: bash

    - if: ${{steps.chrome_browser_download.outputs.cache-hit != 'true' && steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: 'cache mermaid browser'
      uses: actions/cache/save@v6.1.0
      with:
        key: mermaid-maker-chrome-browser-11.16.0
        path: mermaid-maker-chrome-browser

      # basic though process for next step:
      # if output_dir is the same:
        # generate file with new suffix
      # if output_dir diff
        # extract file name
        # place under new dir
        # generate file with new suffix 
      
    - if: ${{steps.changed_files.outputs.CHANGED_FILES != ''}}
      id: mermaid-gen
      name: Generate mermaid diagrams
      env:
        ALL_CHANGED_FILES: ${{steps.changed_files.outputs.CHANGED_FILES}}
        MERMAID_ENV: PUPPETEER_CACHE_DIR=mermaid-maker-chrome-browser aa-exec --profile=chrome
        RUN_CMD: ${{steps.set_pkg_manager_run.outputs.pkg_manager_run_cmd}}
      run: |
          import os
          import json
          from subprocess import run
          from pathlib import Path

          output_file_arr = []
          mermaid_env = [
              "PUPPETEER_CACHE_DIR=mermaid-maker-chrome-browser aa-exec",
              "--profile=chrome",
          ]

          # generate mermaid diagram for each changed file
          for file in "${{env.ALL_CHANGED_FILES}}".split("\n"):
              if "${{inputs.output_dir}}" == "same":
                  output_file = file + ".${{inputs.output_file_extension}}"
                  output_file_arr.append(output_file)

                  # use env variable to specify custom browser location
                  # use aa-exec --profile chrome to sandbox puppeteer's chrome executoin
                  # generate output files with transparent background
                  mermaid_cmd = [
                      "mmdc",
                      "-i",
                      file + ".${{inputs.input_file_extension}}",
                      "-o",
                      output_file,
                      "-b",
                      "transparent",
                  ]

                  run(
                      mermaid_env + ["${{env.RUN_CMD}}"] + mermaid_cmd,
                  )

              else:
                  # use user specified output dir
                  output_file = (Path("${{inputs.output_dir}}") / file).with_suffix(
                      "${{inputs.output_file_extension}}"
                  )
                  output_file_arr.append(output_file)

                  mermaid_cmd = [
                      "mmdc",
                      "-i",
                      file + ".${{inputs.input_file_extension}}",
                      "-o",
                      output_file,
                      "-b",
                      "transparent",
                  ]

                  run(
                      mermaid_env + ["${{env.RUN_CMD}}"] + mermaid_cmd,
                  )

          with open(os.environ["GITHUB_OUTPUT"]) as file:
              print(f"OUTPUTTED_FILES={json.dumps(output_file_arr)}", file=file)


      shell: python
    
    - if: ${{inputs.commit_message == '' && steps.changed_files.outputs.CHANGED_FILES != ''}}
      name: set commit message
      id: COMMIT_MSG
      run: |
        echo "SET_COMMIT_MSG='feat: Convert .${{inputs.input_file_extension}} file(s) to ${{inputs.output_file_extension}}'" >> "$GITHUB_OUTPUT"
      shell: bash

    - if: ${{steps.changed_files.outputs.CHANGED_FILES != ''}}
      uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10.0.0
      with:
        message: ${{steps.COMMIT_MSG.outputs.SET_COMMIT_MSG}}
        # the github action will run git add for each file in the array
        add: ${{steps.mermaid-gen.outputs.OUTPUTTED_FILES}}
