name: Mermaid Maker 
description: Convert mermaid files into image formats.
inputs:
  input_dir:
    description: the input directory for mermaid files
    required: false
    default: "all"
  input_file_extension:
    description: the extension of the mermaid files
    required: false
    default: "mmd"
  output_dir:
    description: the output directory for generated mermaid files
    required: false
    default: "same" 
  output_file_extension:
    description: the output format of the generated mermaid files
    required: false
    default: "svg"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

runs:
  using: composite
  steps:
    - uses: "actions/checkout@main"
      with:
        token: ${{github.token}}
    - uses: "actions/setup-node@main"
      with: 
        node-version: 26
    - run: npm install -g @mermaid-js/mermaid-cli
      shell: bash
    - uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      id: changed_files
      with: 
        files: |
          **.${{inputs.input_file_extension}}
    - if: ${{steps.changed_files.outputs.any_changed == 'true'}}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
            aa-exec --profile=chrome mmdc -i $file -o "$file".svg -b transparent
        done
      shell: bash
    - uses: EndBug/add-and-commit@v10
      with:
        message: "feat: Convert .mmd file(s) to svg"
    