name: mermaid workflow
on: 
    push:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: "actions/checkout@main"
            - uses: "./.github/actions/mermaid-maker"
              with:
                token: ${{github.token}}

    