name: mermaid workflow
on: 
    push:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - uses: "ahmed33033/mermaid-maker@main"
              with:
                token: ${{github.token}}

    